/* eslint-disable */
// This file is auto-generated by scripts/generate-directory-taxonomy.ts.
// Do not edit manually.

export type GeneratedDirectoryTaxonomyAccent = "blue" | "pink" | "purple" | "green";

export interface GeneratedDirectoryTaxonomyCategory {
  id: string;
  label: string;
  rawValue: string;
  count: number;
  accent: GeneratedDirectoryTaxonomyAccent;
}

export interface GeneratedDirectoryTaxonomySection {
  id: "productType" | "domain" | "scope";
  title: string;
  description: string;
  categories: GeneratedDirectoryTaxonomyCategory[];
}

export const GENERATED_DIRECTORY_TAXONOMY: GeneratedDirectoryTaxonomySection[] = [
  {
    "id": "productType",
    "title": "Product Type",
    "description": "How the app is categorized as a product in the directory taxonomy.",
    "categories": [
      {
        "id": "productType-creator-tool",
        "label": "Creator Tool",
        "rawValue": "creator_tool",
        "count": 55,
        "accent": "pink"
      },
      {
        "id": "productType-client",
        "label": "Client",
        "rawValue": "client",
        "count": 42,
        "accent": "green"
      },
      {
        "id": "productType-analytics-tool",
        "label": "Analytics Tool",
        "rawValue": "analytics_tool",
        "count": 28,
        "accent": "pink"
      },
      {
        "id": "productType-account-tool",
        "label": "Account Tool",
        "rawValue": "account_tool",
        "count": 26,
        "accent": "purple"
      },
      {
        "id": "productType-standalone-app",
        "label": "Standalone App",
        "rawValue": "standalone_app",
        "count": 20,
        "accent": "pink"
      },
      {
        "id": "productType-developer-tool",
        "label": "Developer Tool",
        "rawValue": "developer_tool",
        "count": 6,
        "accent": "green"
      },
      {
        "id": "productType-integration",
        "label": "Integration",
        "rawValue": "integration",
        "count": 5,
        "accent": "blue"
      }
    ]
  },
  {
    "id": "domain",
    "title": "Domain",
    "description": "What workflow or problem space the app primarily serves.",
    "categories": [
      {
        "id": "domain-community-social",
        "label": "Community Social",
        "rawValue": "community_social",
        "count": 58,
        "accent": "blue"
      },
      {
        "id": "domain-analytics",
        "label": "Analytics",
        "rawValue": "analytics",
        "count": 27,
        "accent": "pink"
      },
      {
        "id": "domain-scheduling",
        "label": "Scheduling",
        "rawValue": "scheduling",
        "count": 17,
        "accent": "green"
      },
      {
        "id": "domain-account-management",
        "label": "Account Management",
        "rawValue": "account_management",
        "count": 14,
        "accent": "purple"
      },
      {
        "id": "domain-profile-identity",
        "label": "Profile Identity",
        "rawValue": "profile_identity",
        "count": 10,
        "accent": "green"
      },
      {
        "id": "domain-discovery",
        "label": "Discovery",
        "rawValue": "discovery",
        "count": 9,
        "accent": "pink"
      },
      {
        "id": "domain-bookmarks",
        "label": "Bookmarks",
        "rawValue": "bookmarks",
        "count": 8,
        "accent": "purple"
      },
      {
        "id": "domain-posting",
        "label": "Posting",
        "rawValue": "posting",
        "count": 7,
        "accent": "pink"
      },
      {
        "id": "domain-embeds-sharing",
        "label": "Embeds Sharing",
        "rawValue": "embeds_sharing",
        "count": 6,
        "accent": "blue"
      },
      {
        "id": "domain-developer-infra",
        "label": "Developer Infra",
        "rawValue": "developer_infra",
        "count": 5,
        "accent": "purple"
      },
      {
        "id": "domain-moderation-safety",
        "label": "Moderation Safety",
        "rawValue": "moderation_safety",
        "count": 5,
        "accent": "purple"
      },
      {
        "id": "domain-productivity",
        "label": "Productivity",
        "rawValue": "productivity",
        "count": 5,
        "accent": "green"
      },
      {
        "id": "domain-automation",
        "label": "Automation",
        "rawValue": "automation",
        "count": 4,
        "accent": "purple"
      },
      {
        "id": "domain-migration",
        "label": "Migration",
        "rawValue": "migration",
        "count": 3,
        "accent": "green"
      },
      {
        "id": "domain-music",
        "label": "Music",
        "rawValue": "music",
        "count": 2,
        "accent": "purple"
      },
      {
        "id": "domain-games",
        "label": "Games",
        "rawValue": "games",
        "count": 1,
        "accent": "purple"
      },
      {
        "id": "domain-marketplace",
        "label": "Marketplace",
        "rawValue": "marketplace",
        "count": 1,
        "accent": "purple"
      }
    ]
  },
  {
    "id": "scope",
    "title": "Scope",
    "description": "How broadly the app applies across Bluesky, ATProto, or other networks.",
    "categories": [
      {
        "id": "scope-bluesky",
        "label": "Bluesky",
        "rawValue": "bluesky",
        "count": 125,
        "accent": "purple"
      },
      {
        "id": "scope-atproto",
        "label": "Atproto",
        "rawValue": "atproto",
        "count": 29,
        "accent": "blue"
      },
      {
        "id": "scope-cross-network",
        "label": "Cross Network",
        "rawValue": "cross-network",
        "count": 28,
        "accent": "blue"
      }
    ]
  }
];
