#!/usr/bin/env node
import "dotenv/config";

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { db, dbClient } from "../src/db/index.server";
import { storeListings } from "../src/db/schema";

type TaxonomyKind = "productType" | "domain" | "scope";
type CategoryAccent = "blue" | "pink" | "purple" | "green";

const CATEGORY_ACCENTS: CategoryAccent[] = ["blue", "pink", "purple", "green"];

function formatLabel(value: string) {
  const normalized = value.trim().replace(/[_-]+/g, " ").replace(/\s+/g, " ");
  if (normalized.length === 0) {
    return value;
  }

  const shouldTitleCase =
    /[_-]/.test(value) ||
    value === value.toLowerCase() ||
    value === value.toUpperCase();

  if (!shouldTitleCase) {
    return normalized;
  }

  return normalized
    .split(" ")
    .map((word) => word[0]?.toUpperCase() + word.slice(1).toLowerCase())
    .join(" ");
}

function getAccent(seed: string): CategoryAccent {
  const hash = Array.from(seed).reduce(
    (sum, character) => sum + character.charCodeAt(0),
    0,
  );

  return CATEGORY_ACCENTS[hash % CATEGORY_ACCENTS.length] ?? "blue";
}

function getSectionDescription(kind: TaxonomyKind) {
  if (kind === "productType") {
    return "How the app is categorized as a product in the directory taxonomy.";
  }

  if (kind === "domain") {
    return "What workflow or problem space the app primarily serves.";
  }

  return "How broadly the app applies across Bluesky, ATProto, or other networks.";
}

function getSectionTitle(kind: TaxonomyKind) {
  if (kind === "productType") return "Product Type";
  if (kind === "domain") return "Domain";
  return "Scope";
}

async function main() {
  const rows = await db
    .select({
      categorySlugs: storeListings.categorySlugs,
    })
    .from(storeListings);

  const productTypeCounts = new Map<string, number>();
  const domainCounts = new Map<string, number>();
  const scopeCounts = new Map<string, number>();

  for (const row of rows) {
    for (const slug of row.categorySlugs ?? []) {
      const trimmed = slug?.trim();
      if (!trimmed) continue;
      scopeCounts.set(trimmed, (scopeCounts.get(trimmed) || 0) + 1);
      const parts = trimmed.split("/").map((s) => s.trim()).filter(Boolean);
      if (parts[0]) {
        productTypeCounts.set(
          parts[0],
          (productTypeCounts.get(parts[0]) || 0) + 1,
        );
      }
      if (parts[1]) {
        domainCounts.set(parts[1], (domainCounts.get(parts[1]) || 0) + 1);
      }
    }
  }

  const countMaps = {
    productType: productTypeCounts,
    domain: domainCounts,
    scope: scopeCounts,
  } as const;

  const sections = (["productType", "domain", "scope"] as const).map((kind) => {
    const counts = countMaps[kind];

    const categories = [...counts.entries()]
      .sort((left, right) => {
        if (right[1] !== left[1]) {
          return right[1] - left[1];
        }

        return left[0].localeCompare(right[0]);
      })
      .map(([rawValue, count]) => ({
        id: `${kind}-${rawValue.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}`,
        label: formatLabel(rawValue),
        rawValue,
        count,
        accent: getAccent(`${kind}-${rawValue}`),
      }));

    return {
      id: kind,
      title: getSectionTitle(kind),
      description: getSectionDescription(kind),
      categories,
    };
  });

  const outputPath = resolve(
    process.cwd(),
    "src/lib/generated-directory-taxonomy.ts",
  );

  const fileContents = `/* eslint-disable */
// This file is auto-generated by scripts/generate-directory-taxonomy.ts.
// Do not edit manually.

export type GeneratedDirectoryTaxonomyAccent = "blue" | "pink" | "purple" | "green";

export interface GeneratedDirectoryTaxonomyCategory {
  id: string;
  label: string;
  rawValue: string;
  count: number;
  accent: GeneratedDirectoryTaxonomyAccent;
}

export interface GeneratedDirectoryTaxonomySection {
  id: "productType" | "domain" | "scope";
  title: string;
  description: string;
  categories: GeneratedDirectoryTaxonomyCategory[];
}

export const GENERATED_DIRECTORY_TAXONOMY: GeneratedDirectoryTaxonomySection[] = ${JSON.stringify(
    sections,
    null,
    2,
  )};
`;

  await writeFile(outputPath, fileContents);
  console.log(`Wrote taxonomy constant to ${outputPath}`);
}

await main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await dbClient.end({ timeout: 5 });
  });
