/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtocolAllRouteImport } from './routes/protocol.all'
import { Route as DevCategoriesRouteImport } from './routes/dev.categories'
import { Route as DevAppTagsRouteImport } from './routes/dev.app-tags'
import { Route as CategoriesAllRouteImport } from './routes/categories.all'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories.$categoryId'
import { Route as AppsTagsRouteImport } from './routes/apps.tags'
import { Route as AppsAllRouteImport } from './routes/apps.all'
import { Route as AppsTagRouteImport } from './routes/apps.$tag'
import { Route as ProductsProductIdIndexRouteImport } from './routes/products.$productId.index'
import { Route as ProductsProductIdReviewsRouteImport } from './routes/products.$productId.reviews'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolAllRoute = ProtocolAllRouteImport.update({
  id: '/protocol/all',
  path: '/protocol/all',
  getParentRoute: () => rootRouteImport,
} as any)
const DevCategoriesRoute = DevCategoriesRouteImport.update({
  id: '/dev/categories',
  path: '/dev/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAppTagsRoute = DevAppTagsRouteImport.update({
  id: '/dev/app-tags',
  path: '/dev/app-tags',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesAllRoute = CategoriesAllRouteImport.update({
  id: '/categories/all',
  path: '/categories/all',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/categories/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTagsRoute = AppsTagsRouteImport.update({
  id: '/apps/tags',
  path: '/apps/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAllRoute = AppsAllRouteImport.update({
  id: '/apps/all',
  path: '/apps/all',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTagRoute = AppsTagRouteImport.update({
  id: '/apps/$tag',
  path: '/apps/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdIndexRoute = ProductsProductIdIndexRouteImport.update({
  id: '/products/$productId/',
  path: '/products/$productId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdReviewsRoute =
  ProductsProductIdReviewsRouteImport.update({
    id: '/products/$productId/reviews',
    path: '/products/$productId/reviews',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps/$tag': typeof AppsTagRoute
  '/apps/all': typeof AppsAllRoute
  '/apps/tags': typeof AppsTagsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/all': typeof CategoriesAllRoute
  '/dev/app-tags': typeof DevAppTagsRoute
  '/dev/categories': typeof DevCategoriesRoute
  '/protocol/all': typeof ProtocolAllRoute
  '/products/$productId/reviews': typeof ProductsProductIdReviewsRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps/$tag': typeof AppsTagRoute
  '/apps/all': typeof AppsAllRoute
  '/apps/tags': typeof AppsTagsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/all': typeof CategoriesAllRoute
  '/dev/app-tags': typeof DevAppTagsRoute
  '/dev/categories': typeof DevCategoriesRoute
  '/protocol/all': typeof ProtocolAllRoute
  '/products/$productId/reviews': typeof ProductsProductIdReviewsRoute
  '/products/$productId': typeof ProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps/$tag': typeof AppsTagRoute
  '/apps/all': typeof AppsAllRoute
  '/apps/tags': typeof AppsTagsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/all': typeof CategoriesAllRoute
  '/dev/app-tags': typeof DevAppTagsRoute
  '/dev/categories': typeof DevCategoriesRoute
  '/protocol/all': typeof ProtocolAllRoute
  '/products/$productId/reviews': typeof ProductsProductIdReviewsRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps/$tag'
    | '/apps/all'
    | '/apps/tags'
    | '/categories/$categoryId'
    | '/categories/all'
    | '/dev/app-tags'
    | '/dev/categories'
    | '/protocol/all'
    | '/products/$productId/reviews'
    | '/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps/$tag'
    | '/apps/all'
    | '/apps/tags'
    | '/categories/$categoryId'
    | '/categories/all'
    | '/dev/app-tags'
    | '/dev/categories'
    | '/protocol/all'
    | '/products/$productId/reviews'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/apps/$tag'
    | '/apps/all'
    | '/apps/tags'
    | '/categories/$categoryId'
    | '/categories/all'
    | '/dev/app-tags'
    | '/dev/categories'
    | '/protocol/all'
    | '/products/$productId/reviews'
    | '/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsTagRoute: typeof AppsTagRoute
  AppsAllRoute: typeof AppsAllRoute
  AppsTagsRoute: typeof AppsTagsRoute
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  CategoriesAllRoute: typeof CategoriesAllRoute
  DevAppTagsRoute: typeof DevAppTagsRoute
  DevCategoriesRoute: typeof DevCategoriesRoute
  ProtocolAllRoute: typeof ProtocolAllRoute
  ProductsProductIdReviewsRoute: typeof ProductsProductIdReviewsRoute
  ProductsProductIdIndexRoute: typeof ProductsProductIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol/all': {
      id: '/protocol/all'
      path: '/protocol/all'
      fullPath: '/protocol/all'
      preLoaderRoute: typeof ProtocolAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/categories': {
      id: '/dev/categories'
      path: '/dev/categories'
      fullPath: '/dev/categories'
      preLoaderRoute: typeof DevCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/app-tags': {
      id: '/dev/app-tags'
      path: '/dev/app-tags'
      fullPath: '/dev/app-tags'
      preLoaderRoute: typeof DevAppTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/all': {
      id: '/categories/all'
      path: '/categories/all'
      fullPath: '/categories/all'
      preLoaderRoute: typeof CategoriesAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/tags': {
      id: '/apps/tags'
      path: '/apps/tags'
      fullPath: '/apps/tags'
      preLoaderRoute: typeof AppsTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/all': {
      id: '/apps/all'
      path: '/apps/all'
      fullPath: '/apps/all'
      preLoaderRoute: typeof AppsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$tag': {
      id: '/apps/$tag'
      path: '/apps/$tag'
      fullPath: '/apps/$tag'
      preLoaderRoute: typeof AppsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId/': {
      id: '/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof ProductsProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId/reviews': {
      id: '/products/$productId/reviews'
      path: '/products/$productId/reviews'
      fullPath: '/products/$productId/reviews'
      preLoaderRoute: typeof ProductsProductIdReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsTagRoute: AppsTagRoute,
  AppsAllRoute: AppsAllRoute,
  AppsTagsRoute: AppsTagsRoute,
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  CategoriesAllRoute: CategoriesAllRoute,
  DevAppTagsRoute: DevAppTagsRoute,
  DevCategoriesRoute: DevCategoriesRoute,
  ProtocolAllRoute: ProtocolAllRoute,
  ProductsProductIdReviewsRoute: ProductsProductIdReviewsRoute,
  ProductsProductIdIndexRoute: ProductsProductIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
