/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HeaderLayoutRouteImport } from './routes/_header-layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OgIndexRouteImport } from './routes/og.index'
import { Route as HeaderLayoutSearchRouteImport } from './routes/_header-layout.search'
import { Route as HeaderLayoutNotificationsRouteImport } from './routes/_header-layout.notifications'
import { Route as HeaderLayoutHomeRouteImport } from './routes/_header-layout.home'
import { Route as HeaderLayoutAdminLayoutRouteImport } from './routes/_header-layout._admin-layout'
import { Route as HeaderLayoutProtocolTagsRouteImport } from './routes/_header-layout.protocol.tags'
import { Route as HeaderLayoutProtocolListingsRouteImport } from './routes/_header-layout.protocol.listings'
import { Route as HeaderLayoutProtocolCategoryRouteImport } from './routes/_header-layout.protocol.$category'
import { Route as HeaderLayoutProfileActorRouteImport } from './routes/_header-layout.profile.$actor'
import { Route as HeaderLayoutProductsCreateRouteImport } from './routes/_header-layout.products.create'
import { Route as HeaderLayoutProductClaimRouteImport } from './routes/_header-layout.product.claim'
import { Route as HeaderLayoutDevCategoriesRouteImport } from './routes/_header-layout.dev.categories'
import { Route as HeaderLayoutDevAppTagsRouteImport } from './routes/_header-layout.dev.app-tags'
import { Route as HeaderLayoutCategoriesCategoryIdRouteImport } from './routes/_header-layout.categories.$categoryId'
import { Route as HeaderLayoutAppsTagsRouteImport } from './routes/_header-layout.apps.tags'
import { Route as HeaderLayoutAppsAllRouteImport } from './routes/_header-layout.apps.all'
import { Route as HeaderLayoutAppsTagRouteImport } from './routes/_header-layout.apps.$tag'
import { Route as HeaderLayoutProductsProductIdIndexRouteImport } from './routes/_header-layout.products.$productId.index'
import { Route as HeaderLayoutEcosystemsAppIndexRouteImport } from './routes/_header-layout.ecosystems.$app.index'
import { Route as HeaderLayoutAdminLayoutAdminIndexRouteImport } from './routes/_header-layout._admin-layout.admin.index'
import { Route as ApiAuthAtprotoSignupRouteImport } from './routes/api.auth.atproto.signup'
import { Route as ApiAuthAtprotoMetadataDotjsonRouteImport } from './routes/api.auth.atproto.metadata[.]json'
import { Route as ApiAuthAtprotoJwksDotjsonRouteImport } from './routes/api.auth.atproto.jwks[.]json'
import { Route as ApiAuthAtprotoCallbackRouteImport } from './routes/api.auth.atproto.callback'
import { Route as ApiAuthAtprotoAuthorizeRouteImport } from './routes/api.auth.atproto.authorize'
import { Route as HeaderLayoutProductsProductIdReviewsRouteImport } from './routes/_header-layout.products.$productId.reviews'
import { Route as HeaderLayoutProductsProductIdMentionsRouteImport } from './routes/_header-layout.products.$productId.mentions'
import { Route as HeaderLayoutProductsProductIdEditRouteImport } from './routes/_header-layout.products.$productId.edit'
import { Route as HeaderLayoutEcosystemsAppAllRouteImport } from './routes/_header-layout.ecosystems.$app.all'
import { Route as HeaderLayoutAdminLayoutAdminUnverifiedListingsRouteImport } from './routes/_header-layout._admin-layout.admin.unverified-listings'
import { Route as HeaderLayoutAdminLayoutAdminPendingClaimsRouteImport } from './routes/_header-layout._admin-layout.admin.pending-claims'
import { Route as HeaderLayoutAdminLayoutAdminManagedListingsRouteImport } from './routes/_header-layout._admin-layout.admin.managed-listings'
import { Route as HeaderLayoutAdminLayoutAdminListingProductAccountsRouteImport } from './routes/_header-layout._admin-layout.admin.listing-product-accounts'
import { Route as HeaderLayoutAdminLayoutAdminHomePageHeroRouteImport } from './routes/_header-layout._admin-layout.admin.home-page-hero'
import { Route as HeaderLayoutAdminLayoutAdminHeroArtRouteImport } from './routes/_header-layout._admin-layout.admin.hero-art'
import { Route as HeaderLayoutAdminLayoutAdminAdminsRouteImport } from './routes/_header-layout._admin-layout.admin.admins'
import { Route as HeaderLayoutAdminLayoutAdminAddListingRouteImport } from './routes/_header-layout._admin-layout.admin.add-listing'
import { Route as HeaderLayoutProductsProductIdReviewsIndexRouteImport } from './routes/_header-layout.products.$productId.reviews.index'
import { Route as HeaderLayoutProductsProductIdReviewsWriteRouteImport } from './routes/_header-layout.products.$productId.reviews.write'
import { Route as HeaderLayoutProductsProductIdReviewsReviewIdEditRouteImport } from './routes/_header-layout.products.$productId.reviews.$reviewId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutRoute = HeaderLayoutRouteImport.update({
  id: '/_header-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgIndexRoute = OgIndexRouteImport.update({
  id: '/og/',
  path: '/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutSearchRoute = HeaderLayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutNotificationsRoute =
  HeaderLayoutNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutHomeRoute = HeaderLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutAdminLayoutRoute = HeaderLayoutAdminLayoutRouteImport.update({
  id: '/_admin-layout',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutProtocolTagsRoute =
  HeaderLayoutProtocolTagsRouteImport.update({
    id: '/protocol/tags',
    path: '/protocol/tags',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProtocolListingsRoute =
  HeaderLayoutProtocolListingsRouteImport.update({
    id: '/protocol/listings',
    path: '/protocol/listings',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProtocolCategoryRoute =
  HeaderLayoutProtocolCategoryRouteImport.update({
    id: '/protocol/$category',
    path: '/protocol/$category',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProfileActorRoute =
  HeaderLayoutProfileActorRouteImport.update({
    id: '/profile/$actor',
    path: '/profile/$actor',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProductsCreateRoute =
  HeaderLayoutProductsCreateRouteImport.update({
    id: '/products/create',
    path: '/products/create',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProductClaimRoute =
  HeaderLayoutProductClaimRouteImport.update({
    id: '/product/claim',
    path: '/product/claim',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutDevCategoriesRoute =
  HeaderLayoutDevCategoriesRouteImport.update({
    id: '/dev/categories',
    path: '/dev/categories',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutDevAppTagsRoute = HeaderLayoutDevAppTagsRouteImport.update({
  id: '/dev/app-tags',
  path: '/dev/app-tags',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutCategoriesCategoryIdRoute =
  HeaderLayoutCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutAppsTagsRoute = HeaderLayoutAppsTagsRouteImport.update({
  id: '/apps/tags',
  path: '/apps/tags',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutAppsAllRoute = HeaderLayoutAppsAllRouteImport.update({
  id: '/apps/all',
  path: '/apps/all',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutAppsTagRoute = HeaderLayoutAppsTagRouteImport.update({
  id: '/apps/$tag',
  path: '/apps/$tag',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutProductsProductIdIndexRoute =
  HeaderLayoutProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutEcosystemsAppIndexRoute =
  HeaderLayoutEcosystemsAppIndexRouteImport.update({
    id: '/ecosystems/$app/',
    path: '/ecosystems/$app/',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminIndexRoute =
  HeaderLayoutAdminLayoutAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const ApiAuthAtprotoSignupRoute = ApiAuthAtprotoSignupRouteImport.update({
  id: '/api/auth/atproto/signup',
  path: '/api/auth/atproto/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoMetadataDotjsonRoute =
  ApiAuthAtprotoMetadataDotjsonRouteImport.update({
    id: '/api/auth/atproto/metadata.json',
    path: '/api/auth/atproto/metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoJwksDotjsonRoute =
  ApiAuthAtprotoJwksDotjsonRouteImport.update({
    id: '/api/auth/atproto/jwks.json',
    path: '/api/auth/atproto/jwks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoCallbackRoute = ApiAuthAtprotoCallbackRouteImport.update({
  id: '/api/auth/atproto/callback',
  path: '/api/auth/atproto/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoAuthorizeRoute = ApiAuthAtprotoAuthorizeRouteImport.update({
  id: '/api/auth/atproto/authorize',
  path: '/api/auth/atproto/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutProductsProductIdReviewsRoute =
  HeaderLayoutProductsProductIdReviewsRouteImport.update({
    id: '/products/$productId/reviews',
    path: '/products/$productId/reviews',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProductsProductIdMentionsRoute =
  HeaderLayoutProductsProductIdMentionsRouteImport.update({
    id: '/products/$productId/mentions',
    path: '/products/$productId/mentions',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProductsProductIdEditRoute =
  HeaderLayoutProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutEcosystemsAppAllRoute =
  HeaderLayoutEcosystemsAppAllRouteImport.update({
    id: '/ecosystems/$app/all',
    path: '/ecosystems/$app/all',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute =
  HeaderLayoutAdminLayoutAdminUnverifiedListingsRouteImport.update({
    id: '/admin/unverified-listings',
    path: '/admin/unverified-listings',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminPendingClaimsRoute =
  HeaderLayoutAdminLayoutAdminPendingClaimsRouteImport.update({
    id: '/admin/pending-claims',
    path: '/admin/pending-claims',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminManagedListingsRoute =
  HeaderLayoutAdminLayoutAdminManagedListingsRouteImport.update({
    id: '/admin/managed-listings',
    path: '/admin/managed-listings',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminListingProductAccountsRoute =
  HeaderLayoutAdminLayoutAdminListingProductAccountsRouteImport.update({
    id: '/admin/listing-product-accounts',
    path: '/admin/listing-product-accounts',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminHomePageHeroRoute =
  HeaderLayoutAdminLayoutAdminHomePageHeroRouteImport.update({
    id: '/admin/home-page-hero',
    path: '/admin/home-page-hero',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminHeroArtRoute =
  HeaderLayoutAdminLayoutAdminHeroArtRouteImport.update({
    id: '/admin/hero-art',
    path: '/admin/hero-art',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminAdminsRoute =
  HeaderLayoutAdminLayoutAdminAdminsRouteImport.update({
    id: '/admin/admins',
    path: '/admin/admins',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminAddListingRoute =
  HeaderLayoutAdminLayoutAdminAddListingRouteImport.update({
    id: '/admin/add-listing',
    path: '/admin/add-listing',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutProductsProductIdReviewsIndexRoute =
  HeaderLayoutProductsProductIdReviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HeaderLayoutProductsProductIdReviewsRoute,
  } as any)
const HeaderLayoutProductsProductIdReviewsWriteRoute =
  HeaderLayoutProductsProductIdReviewsWriteRouteImport.update({
    id: '/write',
    path: '/write',
    getParentRoute: () => HeaderLayoutProductsProductIdReviewsRoute,
  } as any)
const HeaderLayoutProductsProductIdReviewsReviewIdEditRoute =
  HeaderLayoutProductsProductIdReviewsReviewIdEditRouteImport.update({
    id: '/$reviewId/edit',
    path: '/$reviewId/edit',
    getParentRoute: () => HeaderLayoutProductsProductIdReviewsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof HeaderLayoutHomeRoute
  '/notifications': typeof HeaderLayoutNotificationsRoute
  '/search': typeof HeaderLayoutSearchRoute
  '/og/': typeof OgIndexRoute
  '/apps/$tag': typeof HeaderLayoutAppsTagRoute
  '/apps/all': typeof HeaderLayoutAppsAllRoute
  '/apps/tags': typeof HeaderLayoutAppsTagsRoute
  '/categories/$categoryId': typeof HeaderLayoutCategoriesCategoryIdRoute
  '/dev/app-tags': typeof HeaderLayoutDevAppTagsRoute
  '/dev/categories': typeof HeaderLayoutDevCategoriesRoute
  '/product/claim': typeof HeaderLayoutProductClaimRoute
  '/products/create': typeof HeaderLayoutProductsCreateRoute
  '/profile/$actor': typeof HeaderLayoutProfileActorRoute
  '/protocol/$category': typeof HeaderLayoutProtocolCategoryRoute
  '/protocol/listings': typeof HeaderLayoutProtocolListingsRoute
  '/protocol/tags': typeof HeaderLayoutProtocolTagsRoute
  '/admin/add-listing': typeof HeaderLayoutAdminLayoutAdminAddListingRoute
  '/admin/admins': typeof HeaderLayoutAdminLayoutAdminAdminsRoute
  '/admin/hero-art': typeof HeaderLayoutAdminLayoutAdminHeroArtRoute
  '/admin/home-page-hero': typeof HeaderLayoutAdminLayoutAdminHomePageHeroRoute
  '/admin/listing-product-accounts': typeof HeaderLayoutAdminLayoutAdminListingProductAccountsRoute
  '/admin/managed-listings': typeof HeaderLayoutAdminLayoutAdminManagedListingsRoute
  '/admin/pending-claims': typeof HeaderLayoutAdminLayoutAdminPendingClaimsRoute
  '/admin/unverified-listings': typeof HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute
  '/ecosystems/$app/all': typeof HeaderLayoutEcosystemsAppAllRoute
  '/products/$productId/edit': typeof HeaderLayoutProductsProductIdEditRoute
  '/products/$productId/mentions': typeof HeaderLayoutProductsProductIdMentionsRoute
  '/products/$productId/reviews': typeof HeaderLayoutProductsProductIdReviewsRouteWithChildren
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/admin/': typeof HeaderLayoutAdminLayoutAdminIndexRoute
  '/ecosystems/$app/': typeof HeaderLayoutEcosystemsAppIndexRoute
  '/products/$productId/': typeof HeaderLayoutProductsProductIdIndexRoute
  '/products/$productId/reviews/write': typeof HeaderLayoutProductsProductIdReviewsWriteRoute
  '/products/$productId/reviews/': typeof HeaderLayoutProductsProductIdReviewsIndexRoute
  '/products/$productId/reviews/$reviewId/edit': typeof HeaderLayoutProductsProductIdReviewsReviewIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof HeaderLayoutHomeRoute
  '/notifications': typeof HeaderLayoutNotificationsRoute
  '/search': typeof HeaderLayoutSearchRoute
  '/og': typeof OgIndexRoute
  '/apps/$tag': typeof HeaderLayoutAppsTagRoute
  '/apps/all': typeof HeaderLayoutAppsAllRoute
  '/apps/tags': typeof HeaderLayoutAppsTagsRoute
  '/categories/$categoryId': typeof HeaderLayoutCategoriesCategoryIdRoute
  '/dev/app-tags': typeof HeaderLayoutDevAppTagsRoute
  '/dev/categories': typeof HeaderLayoutDevCategoriesRoute
  '/product/claim': typeof HeaderLayoutProductClaimRoute
  '/products/create': typeof HeaderLayoutProductsCreateRoute
  '/profile/$actor': typeof HeaderLayoutProfileActorRoute
  '/protocol/$category': typeof HeaderLayoutProtocolCategoryRoute
  '/protocol/listings': typeof HeaderLayoutProtocolListingsRoute
  '/protocol/tags': typeof HeaderLayoutProtocolTagsRoute
  '/admin/add-listing': typeof HeaderLayoutAdminLayoutAdminAddListingRoute
  '/admin/admins': typeof HeaderLayoutAdminLayoutAdminAdminsRoute
  '/admin/hero-art': typeof HeaderLayoutAdminLayoutAdminHeroArtRoute
  '/admin/home-page-hero': typeof HeaderLayoutAdminLayoutAdminHomePageHeroRoute
  '/admin/listing-product-accounts': typeof HeaderLayoutAdminLayoutAdminListingProductAccountsRoute
  '/admin/managed-listings': typeof HeaderLayoutAdminLayoutAdminManagedListingsRoute
  '/admin/pending-claims': typeof HeaderLayoutAdminLayoutAdminPendingClaimsRoute
  '/admin/unverified-listings': typeof HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute
  '/ecosystems/$app/all': typeof HeaderLayoutEcosystemsAppAllRoute
  '/products/$productId/edit': typeof HeaderLayoutProductsProductIdEditRoute
  '/products/$productId/mentions': typeof HeaderLayoutProductsProductIdMentionsRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/admin': typeof HeaderLayoutAdminLayoutAdminIndexRoute
  '/ecosystems/$app': typeof HeaderLayoutEcosystemsAppIndexRoute
  '/products/$productId': typeof HeaderLayoutProductsProductIdIndexRoute
  '/products/$productId/reviews/write': typeof HeaderLayoutProductsProductIdReviewsWriteRoute
  '/products/$productId/reviews': typeof HeaderLayoutProductsProductIdReviewsIndexRoute
  '/products/$productId/reviews/$reviewId/edit': typeof HeaderLayoutProductsProductIdReviewsReviewIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_header-layout': typeof HeaderLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_header-layout/_admin-layout': typeof HeaderLayoutAdminLayoutRouteWithChildren
  '/_header-layout/home': typeof HeaderLayoutHomeRoute
  '/_header-layout/notifications': typeof HeaderLayoutNotificationsRoute
  '/_header-layout/search': typeof HeaderLayoutSearchRoute
  '/og/': typeof OgIndexRoute
  '/_header-layout/apps/$tag': typeof HeaderLayoutAppsTagRoute
  '/_header-layout/apps/all': typeof HeaderLayoutAppsAllRoute
  '/_header-layout/apps/tags': typeof HeaderLayoutAppsTagsRoute
  '/_header-layout/categories/$categoryId': typeof HeaderLayoutCategoriesCategoryIdRoute
  '/_header-layout/dev/app-tags': typeof HeaderLayoutDevAppTagsRoute
  '/_header-layout/dev/categories': typeof HeaderLayoutDevCategoriesRoute
  '/_header-layout/product/claim': typeof HeaderLayoutProductClaimRoute
  '/_header-layout/products/create': typeof HeaderLayoutProductsCreateRoute
  '/_header-layout/profile/$actor': typeof HeaderLayoutProfileActorRoute
  '/_header-layout/protocol/$category': typeof HeaderLayoutProtocolCategoryRoute
  '/_header-layout/protocol/listings': typeof HeaderLayoutProtocolListingsRoute
  '/_header-layout/protocol/tags': typeof HeaderLayoutProtocolTagsRoute
  '/_header-layout/_admin-layout/admin/add-listing': typeof HeaderLayoutAdminLayoutAdminAddListingRoute
  '/_header-layout/_admin-layout/admin/admins': typeof HeaderLayoutAdminLayoutAdminAdminsRoute
  '/_header-layout/_admin-layout/admin/hero-art': typeof HeaderLayoutAdminLayoutAdminHeroArtRoute
  '/_header-layout/_admin-layout/admin/home-page-hero': typeof HeaderLayoutAdminLayoutAdminHomePageHeroRoute
  '/_header-layout/_admin-layout/admin/listing-product-accounts': typeof HeaderLayoutAdminLayoutAdminListingProductAccountsRoute
  '/_header-layout/_admin-layout/admin/managed-listings': typeof HeaderLayoutAdminLayoutAdminManagedListingsRoute
  '/_header-layout/_admin-layout/admin/pending-claims': typeof HeaderLayoutAdminLayoutAdminPendingClaimsRoute
  '/_header-layout/_admin-layout/admin/unverified-listings': typeof HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute
  '/_header-layout/ecosystems/$app/all': typeof HeaderLayoutEcosystemsAppAllRoute
  '/_header-layout/products/$productId/edit': typeof HeaderLayoutProductsProductIdEditRoute
  '/_header-layout/products/$productId/mentions': typeof HeaderLayoutProductsProductIdMentionsRoute
  '/_header-layout/products/$productId/reviews': typeof HeaderLayoutProductsProductIdReviewsRouteWithChildren
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/_header-layout/_admin-layout/admin/': typeof HeaderLayoutAdminLayoutAdminIndexRoute
  '/_header-layout/ecosystems/$app/': typeof HeaderLayoutEcosystemsAppIndexRoute
  '/_header-layout/products/$productId/': typeof HeaderLayoutProductsProductIdIndexRoute
  '/_header-layout/products/$productId/reviews/write': typeof HeaderLayoutProductsProductIdReviewsWriteRoute
  '/_header-layout/products/$productId/reviews/': typeof HeaderLayoutProductsProductIdReviewsIndexRoute
  '/_header-layout/products/$productId/reviews/$reviewId/edit': typeof HeaderLayoutProductsProductIdReviewsReviewIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/home'
    | '/notifications'
    | '/search'
    | '/og/'
    | '/apps/$tag'
    | '/apps/all'
    | '/apps/tags'
    | '/categories/$categoryId'
    | '/dev/app-tags'
    | '/dev/categories'
    | '/product/claim'
    | '/products/create'
    | '/profile/$actor'
    | '/protocol/$category'
    | '/protocol/listings'
    | '/protocol/tags'
    | '/admin/add-listing'
    | '/admin/admins'
    | '/admin/hero-art'
    | '/admin/home-page-hero'
    | '/admin/listing-product-accounts'
    | '/admin/managed-listings'
    | '/admin/pending-claims'
    | '/admin/unverified-listings'
    | '/ecosystems/$app/all'
    | '/products/$productId/edit'
    | '/products/$productId/mentions'
    | '/products/$productId/reviews'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/admin/'
    | '/ecosystems/$app/'
    | '/products/$productId/'
    | '/products/$productId/reviews/write'
    | '/products/$productId/reviews/'
    | '/products/$productId/reviews/$reviewId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/home'
    | '/notifications'
    | '/search'
    | '/og'
    | '/apps/$tag'
    | '/apps/all'
    | '/apps/tags'
    | '/categories/$categoryId'
    | '/dev/app-tags'
    | '/dev/categories'
    | '/product/claim'
    | '/products/create'
    | '/profile/$actor'
    | '/protocol/$category'
    | '/protocol/listings'
    | '/protocol/tags'
    | '/admin/add-listing'
    | '/admin/admins'
    | '/admin/hero-art'
    | '/admin/home-page-hero'
    | '/admin/listing-product-accounts'
    | '/admin/managed-listings'
    | '/admin/pending-claims'
    | '/admin/unverified-listings'
    | '/ecosystems/$app/all'
    | '/products/$productId/edit'
    | '/products/$productId/mentions'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/admin'
    | '/ecosystems/$app'
    | '/products/$productId'
    | '/products/$productId/reviews/write'
    | '/products/$productId/reviews'
    | '/products/$productId/reviews/$reviewId/edit'
  id:
    | '__root__'
    | '/'
    | '/_header-layout'
    | '/login'
    | '/_header-layout/_admin-layout'
    | '/_header-layout/home'
    | '/_header-layout/notifications'
    | '/_header-layout/search'
    | '/og/'
    | '/_header-layout/apps/$tag'
    | '/_header-layout/apps/all'
    | '/_header-layout/apps/tags'
    | '/_header-layout/categories/$categoryId'
    | '/_header-layout/dev/app-tags'
    | '/_header-layout/dev/categories'
    | '/_header-layout/product/claim'
    | '/_header-layout/products/create'
    | '/_header-layout/profile/$actor'
    | '/_header-layout/protocol/$category'
    | '/_header-layout/protocol/listings'
    | '/_header-layout/protocol/tags'
    | '/_header-layout/_admin-layout/admin/add-listing'
    | '/_header-layout/_admin-layout/admin/admins'
    | '/_header-layout/_admin-layout/admin/hero-art'
    | '/_header-layout/_admin-layout/admin/home-page-hero'
    | '/_header-layout/_admin-layout/admin/listing-product-accounts'
    | '/_header-layout/_admin-layout/admin/managed-listings'
    | '/_header-layout/_admin-layout/admin/pending-claims'
    | '/_header-layout/_admin-layout/admin/unverified-listings'
    | '/_header-layout/ecosystems/$app/all'
    | '/_header-layout/products/$productId/edit'
    | '/_header-layout/products/$productId/mentions'
    | '/_header-layout/products/$productId/reviews'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/_header-layout/_admin-layout/admin/'
    | '/_header-layout/ecosystems/$app/'
    | '/_header-layout/products/$productId/'
    | '/_header-layout/products/$productId/reviews/write'
    | '/_header-layout/products/$productId/reviews/'
    | '/_header-layout/products/$productId/reviews/$reviewId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeaderLayoutRoute: typeof HeaderLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  OgIndexRoute: typeof OgIndexRoute
  ApiAuthAtprotoAuthorizeRoute: typeof ApiAuthAtprotoAuthorizeRoute
  ApiAuthAtprotoCallbackRoute: typeof ApiAuthAtprotoCallbackRoute
  ApiAuthAtprotoJwksDotjsonRoute: typeof ApiAuthAtprotoJwksDotjsonRoute
  ApiAuthAtprotoMetadataDotjsonRoute: typeof ApiAuthAtprotoMetadataDotjsonRoute
  ApiAuthAtprotoSignupRoute: typeof ApiAuthAtprotoSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout': {
      id: '/_header-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/': {
      id: '/og/'
      path: '/og'
      fullPath: '/og/'
      preLoaderRoute: typeof OgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/search': {
      id: '/_header-layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof HeaderLayoutSearchRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/notifications': {
      id: '/_header-layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof HeaderLayoutNotificationsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/home': {
      id: '/_header-layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HeaderLayoutHomeRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/_admin-layout': {
      id: '/_header-layout/_admin-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/protocol/tags': {
      id: '/_header-layout/protocol/tags'
      path: '/protocol/tags'
      fullPath: '/protocol/tags'
      preLoaderRoute: typeof HeaderLayoutProtocolTagsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/protocol/listings': {
      id: '/_header-layout/protocol/listings'
      path: '/protocol/listings'
      fullPath: '/protocol/listings'
      preLoaderRoute: typeof HeaderLayoutProtocolListingsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/protocol/$category': {
      id: '/_header-layout/protocol/$category'
      path: '/protocol/$category'
      fullPath: '/protocol/$category'
      preLoaderRoute: typeof HeaderLayoutProtocolCategoryRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/profile/$actor': {
      id: '/_header-layout/profile/$actor'
      path: '/profile/$actor'
      fullPath: '/profile/$actor'
      preLoaderRoute: typeof HeaderLayoutProfileActorRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/products/create': {
      id: '/_header-layout/products/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof HeaderLayoutProductsCreateRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/product/claim': {
      id: '/_header-layout/product/claim'
      path: '/product/claim'
      fullPath: '/product/claim'
      preLoaderRoute: typeof HeaderLayoutProductClaimRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/dev/categories': {
      id: '/_header-layout/dev/categories'
      path: '/dev/categories'
      fullPath: '/dev/categories'
      preLoaderRoute: typeof HeaderLayoutDevCategoriesRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/dev/app-tags': {
      id: '/_header-layout/dev/app-tags'
      path: '/dev/app-tags'
      fullPath: '/dev/app-tags'
      preLoaderRoute: typeof HeaderLayoutDevAppTagsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/categories/$categoryId': {
      id: '/_header-layout/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof HeaderLayoutCategoriesCategoryIdRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/apps/tags': {
      id: '/_header-layout/apps/tags'
      path: '/apps/tags'
      fullPath: '/apps/tags'
      preLoaderRoute: typeof HeaderLayoutAppsTagsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/apps/all': {
      id: '/_header-layout/apps/all'
      path: '/apps/all'
      fullPath: '/apps/all'
      preLoaderRoute: typeof HeaderLayoutAppsAllRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/apps/$tag': {
      id: '/_header-layout/apps/$tag'
      path: '/apps/$tag'
      fullPath: '/apps/$tag'
      preLoaderRoute: typeof HeaderLayoutAppsTagRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/products/$productId/': {
      id: '/_header-layout/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdIndexRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/ecosystems/$app/': {
      id: '/_header-layout/ecosystems/$app/'
      path: '/ecosystems/$app'
      fullPath: '/ecosystems/$app/'
      preLoaderRoute: typeof HeaderLayoutEcosystemsAppIndexRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/': {
      id: '/_header-layout/_admin-layout/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminIndexRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/api/auth/atproto/signup': {
      id: '/api/auth/atproto/signup'
      path: '/api/auth/atproto/signup'
      fullPath: '/api/auth/atproto/signup'
      preLoaderRoute: typeof ApiAuthAtprotoSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/metadata.json': {
      id: '/api/auth/atproto/metadata.json'
      path: '/api/auth/atproto/metadata.json'
      fullPath: '/api/auth/atproto/metadata.json'
      preLoaderRoute: typeof ApiAuthAtprotoMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/jwks.json': {
      id: '/api/auth/atproto/jwks.json'
      path: '/api/auth/atproto/jwks.json'
      fullPath: '/api/auth/atproto/jwks.json'
      preLoaderRoute: typeof ApiAuthAtprotoJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/callback': {
      id: '/api/auth/atproto/callback'
      path: '/api/auth/atproto/callback'
      fullPath: '/api/auth/atproto/callback'
      preLoaderRoute: typeof ApiAuthAtprotoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/authorize': {
      id: '/api/auth/atproto/authorize'
      path: '/api/auth/atproto/authorize'
      fullPath: '/api/auth/atproto/authorize'
      preLoaderRoute: typeof ApiAuthAtprotoAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/products/$productId/reviews': {
      id: '/_header-layout/products/$productId/reviews'
      path: '/products/$productId/reviews'
      fullPath: '/products/$productId/reviews'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdReviewsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/products/$productId/mentions': {
      id: '/_header-layout/products/$productId/mentions'
      path: '/products/$productId/mentions'
      fullPath: '/products/$productId/mentions'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdMentionsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/products/$productId/edit': {
      id: '/_header-layout/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdEditRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/ecosystems/$app/all': {
      id: '/_header-layout/ecosystems/$app/all'
      path: '/ecosystems/$app/all'
      fullPath: '/ecosystems/$app/all'
      preLoaderRoute: typeof HeaderLayoutEcosystemsAppAllRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/unverified-listings': {
      id: '/_header-layout/_admin-layout/admin/unverified-listings'
      path: '/admin/unverified-listings'
      fullPath: '/admin/unverified-listings'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminUnverifiedListingsRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/pending-claims': {
      id: '/_header-layout/_admin-layout/admin/pending-claims'
      path: '/admin/pending-claims'
      fullPath: '/admin/pending-claims'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminPendingClaimsRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/managed-listings': {
      id: '/_header-layout/_admin-layout/admin/managed-listings'
      path: '/admin/managed-listings'
      fullPath: '/admin/managed-listings'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminManagedListingsRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/listing-product-accounts': {
      id: '/_header-layout/_admin-layout/admin/listing-product-accounts'
      path: '/admin/listing-product-accounts'
      fullPath: '/admin/listing-product-accounts'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminListingProductAccountsRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/home-page-hero': {
      id: '/_header-layout/_admin-layout/admin/home-page-hero'
      path: '/admin/home-page-hero'
      fullPath: '/admin/home-page-hero'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminHomePageHeroRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/hero-art': {
      id: '/_header-layout/_admin-layout/admin/hero-art'
      path: '/admin/hero-art'
      fullPath: '/admin/hero-art'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminHeroArtRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/admins': {
      id: '/_header-layout/_admin-layout/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminAdminsRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/add-listing': {
      id: '/_header-layout/_admin-layout/admin/add-listing'
      path: '/admin/add-listing'
      fullPath: '/admin/add-listing'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminAddListingRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/products/$productId/reviews/': {
      id: '/_header-layout/products/$productId/reviews/'
      path: '/'
      fullPath: '/products/$productId/reviews/'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdReviewsIndexRouteImport
      parentRoute: typeof HeaderLayoutProductsProductIdReviewsRoute
    }
    '/_header-layout/products/$productId/reviews/write': {
      id: '/_header-layout/products/$productId/reviews/write'
      path: '/write'
      fullPath: '/products/$productId/reviews/write'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdReviewsWriteRouteImport
      parentRoute: typeof HeaderLayoutProductsProductIdReviewsRoute
    }
    '/_header-layout/products/$productId/reviews/$reviewId/edit': {
      id: '/_header-layout/products/$productId/reviews/$reviewId/edit'
      path: '/$reviewId/edit'
      fullPath: '/products/$productId/reviews/$reviewId/edit'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdReviewsReviewIdEditRouteImport
      parentRoute: typeof HeaderLayoutProductsProductIdReviewsRoute
    }
  }
}

interface HeaderLayoutAdminLayoutRouteChildren {
  HeaderLayoutAdminLayoutAdminAddListingRoute: typeof HeaderLayoutAdminLayoutAdminAddListingRoute
  HeaderLayoutAdminLayoutAdminAdminsRoute: typeof HeaderLayoutAdminLayoutAdminAdminsRoute
  HeaderLayoutAdminLayoutAdminHeroArtRoute: typeof HeaderLayoutAdminLayoutAdminHeroArtRoute
  HeaderLayoutAdminLayoutAdminHomePageHeroRoute: typeof HeaderLayoutAdminLayoutAdminHomePageHeroRoute
  HeaderLayoutAdminLayoutAdminListingProductAccountsRoute: typeof HeaderLayoutAdminLayoutAdminListingProductAccountsRoute
  HeaderLayoutAdminLayoutAdminManagedListingsRoute: typeof HeaderLayoutAdminLayoutAdminManagedListingsRoute
  HeaderLayoutAdminLayoutAdminPendingClaimsRoute: typeof HeaderLayoutAdminLayoutAdminPendingClaimsRoute
  HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute: typeof HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute
  HeaderLayoutAdminLayoutAdminIndexRoute: typeof HeaderLayoutAdminLayoutAdminIndexRoute
}

const HeaderLayoutAdminLayoutRouteChildren: HeaderLayoutAdminLayoutRouteChildren =
  {
    HeaderLayoutAdminLayoutAdminAddListingRoute:
      HeaderLayoutAdminLayoutAdminAddListingRoute,
    HeaderLayoutAdminLayoutAdminAdminsRoute:
      HeaderLayoutAdminLayoutAdminAdminsRoute,
    HeaderLayoutAdminLayoutAdminHeroArtRoute:
      HeaderLayoutAdminLayoutAdminHeroArtRoute,
    HeaderLayoutAdminLayoutAdminHomePageHeroRoute:
      HeaderLayoutAdminLayoutAdminHomePageHeroRoute,
    HeaderLayoutAdminLayoutAdminListingProductAccountsRoute:
      HeaderLayoutAdminLayoutAdminListingProductAccountsRoute,
    HeaderLayoutAdminLayoutAdminManagedListingsRoute:
      HeaderLayoutAdminLayoutAdminManagedListingsRoute,
    HeaderLayoutAdminLayoutAdminPendingClaimsRoute:
      HeaderLayoutAdminLayoutAdminPendingClaimsRoute,
    HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute:
      HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute,
    HeaderLayoutAdminLayoutAdminIndexRoute:
      HeaderLayoutAdminLayoutAdminIndexRoute,
  }

const HeaderLayoutAdminLayoutRouteWithChildren =
  HeaderLayoutAdminLayoutRoute._addFileChildren(
    HeaderLayoutAdminLayoutRouteChildren,
  )

interface HeaderLayoutProductsProductIdReviewsRouteChildren {
  HeaderLayoutProductsProductIdReviewsWriteRoute: typeof HeaderLayoutProductsProductIdReviewsWriteRoute
  HeaderLayoutProductsProductIdReviewsIndexRoute: typeof HeaderLayoutProductsProductIdReviewsIndexRoute
  HeaderLayoutProductsProductIdReviewsReviewIdEditRoute: typeof HeaderLayoutProductsProductIdReviewsReviewIdEditRoute
}

const HeaderLayoutProductsProductIdReviewsRouteChildren: HeaderLayoutProductsProductIdReviewsRouteChildren =
  {
    HeaderLayoutProductsProductIdReviewsWriteRoute:
      HeaderLayoutProductsProductIdReviewsWriteRoute,
    HeaderLayoutProductsProductIdReviewsIndexRoute:
      HeaderLayoutProductsProductIdReviewsIndexRoute,
    HeaderLayoutProductsProductIdReviewsReviewIdEditRoute:
      HeaderLayoutProductsProductIdReviewsReviewIdEditRoute,
  }

const HeaderLayoutProductsProductIdReviewsRouteWithChildren =
  HeaderLayoutProductsProductIdReviewsRoute._addFileChildren(
    HeaderLayoutProductsProductIdReviewsRouteChildren,
  )

interface HeaderLayoutRouteChildren {
  HeaderLayoutAdminLayoutRoute: typeof HeaderLayoutAdminLayoutRouteWithChildren
  HeaderLayoutHomeRoute: typeof HeaderLayoutHomeRoute
  HeaderLayoutNotificationsRoute: typeof HeaderLayoutNotificationsRoute
  HeaderLayoutSearchRoute: typeof HeaderLayoutSearchRoute
  HeaderLayoutAppsTagRoute: typeof HeaderLayoutAppsTagRoute
  HeaderLayoutAppsAllRoute: typeof HeaderLayoutAppsAllRoute
  HeaderLayoutAppsTagsRoute: typeof HeaderLayoutAppsTagsRoute
  HeaderLayoutCategoriesCategoryIdRoute: typeof HeaderLayoutCategoriesCategoryIdRoute
  HeaderLayoutDevAppTagsRoute: typeof HeaderLayoutDevAppTagsRoute
  HeaderLayoutDevCategoriesRoute: typeof HeaderLayoutDevCategoriesRoute
  HeaderLayoutProductClaimRoute: typeof HeaderLayoutProductClaimRoute
  HeaderLayoutProductsCreateRoute: typeof HeaderLayoutProductsCreateRoute
  HeaderLayoutProfileActorRoute: typeof HeaderLayoutProfileActorRoute
  HeaderLayoutProtocolCategoryRoute: typeof HeaderLayoutProtocolCategoryRoute
  HeaderLayoutProtocolListingsRoute: typeof HeaderLayoutProtocolListingsRoute
  HeaderLayoutProtocolTagsRoute: typeof HeaderLayoutProtocolTagsRoute
  HeaderLayoutEcosystemsAppAllRoute: typeof HeaderLayoutEcosystemsAppAllRoute
  HeaderLayoutProductsProductIdEditRoute: typeof HeaderLayoutProductsProductIdEditRoute
  HeaderLayoutProductsProductIdMentionsRoute: typeof HeaderLayoutProductsProductIdMentionsRoute
  HeaderLayoutProductsProductIdReviewsRoute: typeof HeaderLayoutProductsProductIdReviewsRouteWithChildren
  HeaderLayoutEcosystemsAppIndexRoute: typeof HeaderLayoutEcosystemsAppIndexRoute
  HeaderLayoutProductsProductIdIndexRoute: typeof HeaderLayoutProductsProductIdIndexRoute
}

const HeaderLayoutRouteChildren: HeaderLayoutRouteChildren = {
  HeaderLayoutAdminLayoutRoute: HeaderLayoutAdminLayoutRouteWithChildren,
  HeaderLayoutHomeRoute: HeaderLayoutHomeRoute,
  HeaderLayoutNotificationsRoute: HeaderLayoutNotificationsRoute,
  HeaderLayoutSearchRoute: HeaderLayoutSearchRoute,
  HeaderLayoutAppsTagRoute: HeaderLayoutAppsTagRoute,
  HeaderLayoutAppsAllRoute: HeaderLayoutAppsAllRoute,
  HeaderLayoutAppsTagsRoute: HeaderLayoutAppsTagsRoute,
  HeaderLayoutCategoriesCategoryIdRoute: HeaderLayoutCategoriesCategoryIdRoute,
  HeaderLayoutDevAppTagsRoute: HeaderLayoutDevAppTagsRoute,
  HeaderLayoutDevCategoriesRoute: HeaderLayoutDevCategoriesRoute,
  HeaderLayoutProductClaimRoute: HeaderLayoutProductClaimRoute,
  HeaderLayoutProductsCreateRoute: HeaderLayoutProductsCreateRoute,
  HeaderLayoutProfileActorRoute: HeaderLayoutProfileActorRoute,
  HeaderLayoutProtocolCategoryRoute: HeaderLayoutProtocolCategoryRoute,
  HeaderLayoutProtocolListingsRoute: HeaderLayoutProtocolListingsRoute,
  HeaderLayoutProtocolTagsRoute: HeaderLayoutProtocolTagsRoute,
  HeaderLayoutEcosystemsAppAllRoute: HeaderLayoutEcosystemsAppAllRoute,
  HeaderLayoutProductsProductIdEditRoute:
    HeaderLayoutProductsProductIdEditRoute,
  HeaderLayoutProductsProductIdMentionsRoute:
    HeaderLayoutProductsProductIdMentionsRoute,
  HeaderLayoutProductsProductIdReviewsRoute:
    HeaderLayoutProductsProductIdReviewsRouteWithChildren,
  HeaderLayoutEcosystemsAppIndexRoute: HeaderLayoutEcosystemsAppIndexRoute,
  HeaderLayoutProductsProductIdIndexRoute:
    HeaderLayoutProductsProductIdIndexRoute,
}

const HeaderLayoutRouteWithChildren = HeaderLayoutRoute._addFileChildren(
  HeaderLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeaderLayoutRoute: HeaderLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  OgIndexRoute: OgIndexRoute,
  ApiAuthAtprotoAuthorizeRoute: ApiAuthAtprotoAuthorizeRoute,
  ApiAuthAtprotoCallbackRoute: ApiAuthAtprotoCallbackRoute,
  ApiAuthAtprotoJwksDotjsonRoute: ApiAuthAtprotoJwksDotjsonRoute,
  ApiAuthAtprotoMetadataDotjsonRoute: ApiAuthAtprotoMetadataDotjsonRoute,
  ApiAuthAtprotoSignupRoute: ApiAuthAtprotoSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
