/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HeaderLayoutRouteImport } from './routes/_header-layout'
import { Route as HeaderLayoutIndexRouteImport } from './routes/_header-layout.index'
import { Route as HeaderLayoutProtocolTagsRouteImport } from './routes/_header-layout.protocol.tags'
import { Route as HeaderLayoutProtocolListingsRouteImport } from './routes/_header-layout.protocol.listings'
import { Route as HeaderLayoutProtocolCategoryRouteImport } from './routes/_header-layout.protocol.$category'
import { Route as HeaderLayoutDevCategoriesRouteImport } from './routes/_header-layout.dev.categories'
import { Route as HeaderLayoutDevAppTagsRouteImport } from './routes/_header-layout.dev.app-tags'
import { Route as HeaderLayoutCategoriesCategoryIdRouteImport } from './routes/_header-layout.categories.$categoryId'
import { Route as HeaderLayoutAppsTagsRouteImport } from './routes/_header-layout.apps.tags'
import { Route as HeaderLayoutAppsAllRouteImport } from './routes/_header-layout.apps.all'
import { Route as HeaderLayoutAppsTagRouteImport } from './routes/_header-layout.apps.$tag'
import { Route as HeaderLayoutProductsProductIdIndexRouteImport } from './routes/_header-layout.products.$productId.index'
import { Route as HeaderLayoutEcosystemsAppIndexRouteImport } from './routes/_header-layout.ecosystems.$app.index'
import { Route as ApiAuthAtprotoSignupRouteImport } from './routes/api.auth.atproto.signup'
import { Route as ApiAuthAtprotoMetadataDotjsonRouteImport } from './routes/api.auth.atproto.metadata[.]json'
import { Route as ApiAuthAtprotoJwksDotjsonRouteImport } from './routes/api.auth.atproto.jwks[.]json'
import { Route as ApiAuthAtprotoCallbackRouteImport } from './routes/api.auth.atproto.callback'
import { Route as ApiAuthAtprotoAuthorizeRouteImport } from './routes/api.auth.atproto.authorize'
import { Route as HeaderLayoutProductsProductIdReviewsRouteImport } from './routes/_header-layout.products.$productId.reviews'
import { Route as HeaderLayoutEcosystemsAppAllRouteImport } from './routes/_header-layout.ecosystems.$app.all'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutRoute = HeaderLayoutRouteImport.update({
  id: '/_header-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutIndexRoute = HeaderLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutProtocolTagsRoute =
  HeaderLayoutProtocolTagsRouteImport.update({
    id: '/protocol/tags',
    path: '/protocol/tags',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProtocolListingsRoute =
  HeaderLayoutProtocolListingsRouteImport.update({
    id: '/protocol/listings',
    path: '/protocol/listings',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProtocolCategoryRoute =
  HeaderLayoutProtocolCategoryRouteImport.update({
    id: '/protocol/$category',
    path: '/protocol/$category',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutDevCategoriesRoute =
  HeaderLayoutDevCategoriesRouteImport.update({
    id: '/dev/categories',
    path: '/dev/categories',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutDevAppTagsRoute = HeaderLayoutDevAppTagsRouteImport.update({
  id: '/dev/app-tags',
  path: '/dev/app-tags',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutCategoriesCategoryIdRoute =
  HeaderLayoutCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutAppsTagsRoute = HeaderLayoutAppsTagsRouteImport.update({
  id: '/apps/tags',
  path: '/apps/tags',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutAppsAllRoute = HeaderLayoutAppsAllRouteImport.update({
  id: '/apps/all',
  path: '/apps/all',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutAppsTagRoute = HeaderLayoutAppsTagRouteImport.update({
  id: '/apps/$tag',
  path: '/apps/$tag',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutProductsProductIdIndexRoute =
  HeaderLayoutProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutEcosystemsAppIndexRoute =
  HeaderLayoutEcosystemsAppIndexRouteImport.update({
    id: '/ecosystems/$app/',
    path: '/ecosystems/$app/',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const ApiAuthAtprotoSignupRoute = ApiAuthAtprotoSignupRouteImport.update({
  id: '/api/auth/atproto/signup',
  path: '/api/auth/atproto/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoMetadataDotjsonRoute =
  ApiAuthAtprotoMetadataDotjsonRouteImport.update({
    id: '/api/auth/atproto/metadata.json',
    path: '/api/auth/atproto/metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoJwksDotjsonRoute =
  ApiAuthAtprotoJwksDotjsonRouteImport.update({
    id: '/api/auth/atproto/jwks.json',
    path: '/api/auth/atproto/jwks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoCallbackRoute = ApiAuthAtprotoCallbackRouteImport.update({
  id: '/api/auth/atproto/callback',
  path: '/api/auth/atproto/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoAuthorizeRoute = ApiAuthAtprotoAuthorizeRouteImport.update({
  id: '/api/auth/atproto/authorize',
  path: '/api/auth/atproto/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutProductsProductIdReviewsRoute =
  HeaderLayoutProductsProductIdReviewsRouteImport.update({
    id: '/products/$productId/reviews',
    path: '/products/$productId/reviews',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutEcosystemsAppAllRoute =
  HeaderLayoutEcosystemsAppAllRouteImport.update({
    id: '/ecosystems/$app/all',
    path: '/ecosystems/$app/all',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof HeaderLayoutIndexRoute
  '/login': typeof LoginRoute
  '/apps/$tag': typeof HeaderLayoutAppsTagRoute
  '/apps/all': typeof HeaderLayoutAppsAllRoute
  '/apps/tags': typeof HeaderLayoutAppsTagsRoute
  '/categories/$categoryId': typeof HeaderLayoutCategoriesCategoryIdRoute
  '/dev/app-tags': typeof HeaderLayoutDevAppTagsRoute
  '/dev/categories': typeof HeaderLayoutDevCategoriesRoute
  '/protocol/$category': typeof HeaderLayoutProtocolCategoryRoute
  '/protocol/listings': typeof HeaderLayoutProtocolListingsRoute
  '/protocol/tags': typeof HeaderLayoutProtocolTagsRoute
  '/ecosystems/$app/all': typeof HeaderLayoutEcosystemsAppAllRoute
  '/products/$productId/reviews': typeof HeaderLayoutProductsProductIdReviewsRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/ecosystems/$app/': typeof HeaderLayoutEcosystemsAppIndexRoute
  '/products/$productId/': typeof HeaderLayoutProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof HeaderLayoutIndexRoute
  '/apps/$tag': typeof HeaderLayoutAppsTagRoute
  '/apps/all': typeof HeaderLayoutAppsAllRoute
  '/apps/tags': typeof HeaderLayoutAppsTagsRoute
  '/categories/$categoryId': typeof HeaderLayoutCategoriesCategoryIdRoute
  '/dev/app-tags': typeof HeaderLayoutDevAppTagsRoute
  '/dev/categories': typeof HeaderLayoutDevCategoriesRoute
  '/protocol/$category': typeof HeaderLayoutProtocolCategoryRoute
  '/protocol/listings': typeof HeaderLayoutProtocolListingsRoute
  '/protocol/tags': typeof HeaderLayoutProtocolTagsRoute
  '/ecosystems/$app/all': typeof HeaderLayoutEcosystemsAppAllRoute
  '/products/$productId/reviews': typeof HeaderLayoutProductsProductIdReviewsRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/ecosystems/$app': typeof HeaderLayoutEcosystemsAppIndexRoute
  '/products/$productId': typeof HeaderLayoutProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_header-layout': typeof HeaderLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_header-layout/': typeof HeaderLayoutIndexRoute
  '/_header-layout/apps/$tag': typeof HeaderLayoutAppsTagRoute
  '/_header-layout/apps/all': typeof HeaderLayoutAppsAllRoute
  '/_header-layout/apps/tags': typeof HeaderLayoutAppsTagsRoute
  '/_header-layout/categories/$categoryId': typeof HeaderLayoutCategoriesCategoryIdRoute
  '/_header-layout/dev/app-tags': typeof HeaderLayoutDevAppTagsRoute
  '/_header-layout/dev/categories': typeof HeaderLayoutDevCategoriesRoute
  '/_header-layout/protocol/$category': typeof HeaderLayoutProtocolCategoryRoute
  '/_header-layout/protocol/listings': typeof HeaderLayoutProtocolListingsRoute
  '/_header-layout/protocol/tags': typeof HeaderLayoutProtocolTagsRoute
  '/_header-layout/ecosystems/$app/all': typeof HeaderLayoutEcosystemsAppAllRoute
  '/_header-layout/products/$productId/reviews': typeof HeaderLayoutProductsProductIdReviewsRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/_header-layout/ecosystems/$app/': typeof HeaderLayoutEcosystemsAppIndexRoute
  '/_header-layout/products/$productId/': typeof HeaderLayoutProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/apps/$tag'
    | '/apps/all'
    | '/apps/tags'
    | '/categories/$categoryId'
    | '/dev/app-tags'
    | '/dev/categories'
    | '/protocol/$category'
    | '/protocol/listings'
    | '/protocol/tags'
    | '/ecosystems/$app/all'
    | '/products/$productId/reviews'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/ecosystems/$app/'
    | '/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/apps/$tag'
    | '/apps/all'
    | '/apps/tags'
    | '/categories/$categoryId'
    | '/dev/app-tags'
    | '/dev/categories'
    | '/protocol/$category'
    | '/protocol/listings'
    | '/protocol/tags'
    | '/ecosystems/$app/all'
    | '/products/$productId/reviews'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/ecosystems/$app'
    | '/products/$productId'
  id:
    | '__root__'
    | '/_header-layout'
    | '/login'
    | '/_header-layout/'
    | '/_header-layout/apps/$tag'
    | '/_header-layout/apps/all'
    | '/_header-layout/apps/tags'
    | '/_header-layout/categories/$categoryId'
    | '/_header-layout/dev/app-tags'
    | '/_header-layout/dev/categories'
    | '/_header-layout/protocol/$category'
    | '/_header-layout/protocol/listings'
    | '/_header-layout/protocol/tags'
    | '/_header-layout/ecosystems/$app/all'
    | '/_header-layout/products/$productId/reviews'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/_header-layout/ecosystems/$app/'
    | '/_header-layout/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HeaderLayoutRoute: typeof HeaderLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthAtprotoAuthorizeRoute: typeof ApiAuthAtprotoAuthorizeRoute
  ApiAuthAtprotoCallbackRoute: typeof ApiAuthAtprotoCallbackRoute
  ApiAuthAtprotoJwksDotjsonRoute: typeof ApiAuthAtprotoJwksDotjsonRoute
  ApiAuthAtprotoMetadataDotjsonRoute: typeof ApiAuthAtprotoMetadataDotjsonRoute
  ApiAuthAtprotoSignupRoute: typeof ApiAuthAtprotoSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout': {
      id: '/_header-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/': {
      id: '/_header-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutIndexRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/protocol/tags': {
      id: '/_header-layout/protocol/tags'
      path: '/protocol/tags'
      fullPath: '/protocol/tags'
      preLoaderRoute: typeof HeaderLayoutProtocolTagsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/protocol/listings': {
      id: '/_header-layout/protocol/listings'
      path: '/protocol/listings'
      fullPath: '/protocol/listings'
      preLoaderRoute: typeof HeaderLayoutProtocolListingsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/protocol/$category': {
      id: '/_header-layout/protocol/$category'
      path: '/protocol/$category'
      fullPath: '/protocol/$category'
      preLoaderRoute: typeof HeaderLayoutProtocolCategoryRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/dev/categories': {
      id: '/_header-layout/dev/categories'
      path: '/dev/categories'
      fullPath: '/dev/categories'
      preLoaderRoute: typeof HeaderLayoutDevCategoriesRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/dev/app-tags': {
      id: '/_header-layout/dev/app-tags'
      path: '/dev/app-tags'
      fullPath: '/dev/app-tags'
      preLoaderRoute: typeof HeaderLayoutDevAppTagsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/categories/$categoryId': {
      id: '/_header-layout/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof HeaderLayoutCategoriesCategoryIdRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/apps/tags': {
      id: '/_header-layout/apps/tags'
      path: '/apps/tags'
      fullPath: '/apps/tags'
      preLoaderRoute: typeof HeaderLayoutAppsTagsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/apps/all': {
      id: '/_header-layout/apps/all'
      path: '/apps/all'
      fullPath: '/apps/all'
      preLoaderRoute: typeof HeaderLayoutAppsAllRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/apps/$tag': {
      id: '/_header-layout/apps/$tag'
      path: '/apps/$tag'
      fullPath: '/apps/$tag'
      preLoaderRoute: typeof HeaderLayoutAppsTagRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/products/$productId/': {
      id: '/_header-layout/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdIndexRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/ecosystems/$app/': {
      id: '/_header-layout/ecosystems/$app/'
      path: '/ecosystems/$app'
      fullPath: '/ecosystems/$app/'
      preLoaderRoute: typeof HeaderLayoutEcosystemsAppIndexRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/api/auth/atproto/signup': {
      id: '/api/auth/atproto/signup'
      path: '/api/auth/atproto/signup'
      fullPath: '/api/auth/atproto/signup'
      preLoaderRoute: typeof ApiAuthAtprotoSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/metadata.json': {
      id: '/api/auth/atproto/metadata.json'
      path: '/api/auth/atproto/metadata.json'
      fullPath: '/api/auth/atproto/metadata.json'
      preLoaderRoute: typeof ApiAuthAtprotoMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/jwks.json': {
      id: '/api/auth/atproto/jwks.json'
      path: '/api/auth/atproto/jwks.json'
      fullPath: '/api/auth/atproto/jwks.json'
      preLoaderRoute: typeof ApiAuthAtprotoJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/callback': {
      id: '/api/auth/atproto/callback'
      path: '/api/auth/atproto/callback'
      fullPath: '/api/auth/atproto/callback'
      preLoaderRoute: typeof ApiAuthAtprotoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/authorize': {
      id: '/api/auth/atproto/authorize'
      path: '/api/auth/atproto/authorize'
      fullPath: '/api/auth/atproto/authorize'
      preLoaderRoute: typeof ApiAuthAtprotoAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/products/$productId/reviews': {
      id: '/_header-layout/products/$productId/reviews'
      path: '/products/$productId/reviews'
      fullPath: '/products/$productId/reviews'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdReviewsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/ecosystems/$app/all': {
      id: '/_header-layout/ecosystems/$app/all'
      path: '/ecosystems/$app/all'
      fullPath: '/ecosystems/$app/all'
      preLoaderRoute: typeof HeaderLayoutEcosystemsAppAllRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
  }
}

interface HeaderLayoutRouteChildren {
  HeaderLayoutIndexRoute: typeof HeaderLayoutIndexRoute
  HeaderLayoutAppsTagRoute: typeof HeaderLayoutAppsTagRoute
  HeaderLayoutAppsAllRoute: typeof HeaderLayoutAppsAllRoute
  HeaderLayoutAppsTagsRoute: typeof HeaderLayoutAppsTagsRoute
  HeaderLayoutCategoriesCategoryIdRoute: typeof HeaderLayoutCategoriesCategoryIdRoute
  HeaderLayoutDevAppTagsRoute: typeof HeaderLayoutDevAppTagsRoute
  HeaderLayoutDevCategoriesRoute: typeof HeaderLayoutDevCategoriesRoute
  HeaderLayoutProtocolCategoryRoute: typeof HeaderLayoutProtocolCategoryRoute
  HeaderLayoutProtocolListingsRoute: typeof HeaderLayoutProtocolListingsRoute
  HeaderLayoutProtocolTagsRoute: typeof HeaderLayoutProtocolTagsRoute
  HeaderLayoutEcosystemsAppAllRoute: typeof HeaderLayoutEcosystemsAppAllRoute
  HeaderLayoutProductsProductIdReviewsRoute: typeof HeaderLayoutProductsProductIdReviewsRoute
  HeaderLayoutEcosystemsAppIndexRoute: typeof HeaderLayoutEcosystemsAppIndexRoute
  HeaderLayoutProductsProductIdIndexRoute: typeof HeaderLayoutProductsProductIdIndexRoute
}

const HeaderLayoutRouteChildren: HeaderLayoutRouteChildren = {
  HeaderLayoutIndexRoute: HeaderLayoutIndexRoute,
  HeaderLayoutAppsTagRoute: HeaderLayoutAppsTagRoute,
  HeaderLayoutAppsAllRoute: HeaderLayoutAppsAllRoute,
  HeaderLayoutAppsTagsRoute: HeaderLayoutAppsTagsRoute,
  HeaderLayoutCategoriesCategoryIdRoute: HeaderLayoutCategoriesCategoryIdRoute,
  HeaderLayoutDevAppTagsRoute: HeaderLayoutDevAppTagsRoute,
  HeaderLayoutDevCategoriesRoute: HeaderLayoutDevCategoriesRoute,
  HeaderLayoutProtocolCategoryRoute: HeaderLayoutProtocolCategoryRoute,
  HeaderLayoutProtocolListingsRoute: HeaderLayoutProtocolListingsRoute,
  HeaderLayoutProtocolTagsRoute: HeaderLayoutProtocolTagsRoute,
  HeaderLayoutEcosystemsAppAllRoute: HeaderLayoutEcosystemsAppAllRoute,
  HeaderLayoutProductsProductIdReviewsRoute:
    HeaderLayoutProductsProductIdReviewsRoute,
  HeaderLayoutEcosystemsAppIndexRoute: HeaderLayoutEcosystemsAppIndexRoute,
  HeaderLayoutProductsProductIdIndexRoute:
    HeaderLayoutProductsProductIdIndexRoute,
}

const HeaderLayoutRouteWithChildren = HeaderLayoutRoute._addFileChildren(
  HeaderLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HeaderLayoutRoute: HeaderLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthAtprotoAuthorizeRoute: ApiAuthAtprotoAuthorizeRoute,
  ApiAuthAtprotoCallbackRoute: ApiAuthAtprotoCallbackRoute,
  ApiAuthAtprotoJwksDotjsonRoute: ApiAuthAtprotoJwksDotjsonRoute,
  ApiAuthAtprotoMetadataDotjsonRoute: ApiAuthAtprotoMetadataDotjsonRoute,
  ApiAuthAtprotoSignupRoute: ApiAuthAtprotoSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
